
volumes:
  hbci_pgadmin_data:
  hbci_db_data:
  hbci_redis_data:

networks:
  dev_hbci_network:
      name: network_hbci

services:

  webserver_hbci:
    container_name: webserver_hbci
    build:
      context: ./.docker/php
    ports:
      - "${HBCI_PHP_WEBSERVER_PORT}:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - db_hbci
      - redis_hbci
    networks:
      - dev_hbci_network
    restart: on-failure
    # after container running in its terminal
    #  bash docker/resources/post_run_compose.sh

  db_hbci:
    container_name: db_hbci
    build:
      context: ./.docker/postgres
    restart: always
    environment:
      POSTGRES_DB: "${HBCI_DATABASE_ROOT_USER}"
      POSTGRES_USER: "${HBCI_DATABASE_ROOT_USER}"
      POSTGRES_PASSWORD: "${HBCI_DATABASE_ROOT_PW}"
      APP_USERNAME: "${HBCI_DATABASE_USER_NAME}"
      APP_PASSWORD: "${HBCI_DATABASE_USER_PW}"
      PGDATAG: /var/lib/postgresql/data
    ports:
      - "${HBCI_DATABASE_PORT}:5432"
    volumes:
      - hbci_db_data:/var/lib/postgresql/data
    networks:
      - dev_hbci_network

  pgadmin_hbci:
    container_name: pgadmin_hbci
    depends_on:
      - db_hbci
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${HBCI_DB_ADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${HBCI_DATABASE_ROOT_PW}"
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "${HBCI_DB_ADMIN_PORT}:80"
    volumes:
      - hbci_pgadmin_data:/var/lib/pgadmin
    networks:
      - dev_hbci_network

  redis_hbci:
    image: redis
    container_name: redis_hbci
    command: redis-server --save 60 1 --loglevel warning --requirepass "${REDIS_PASSWORD}"
    volumes:
        - hbci_redis_data:/var/lib/redis/data
    ports:
        - "${HBCI_REDIS_PORT}:5432"
    networks:
        - dev_hbci_network

